### ISSUE TITLE
Clear corresponding component data of deleted entities

### ISSUE THREAD

**Issue by MauriceZeuner** [TeamAtomECS/AtomECS#31]
Following the nasty heating error in the dipole trap, I'd propose we should think about how to generally clean component data (in each iteration step). Two things come to mind:

1. We could just clear ALL dynamical components every step, like we do with `Force`. Pro: clean, Con: additional code that runs every step
2. We could make a more dedicated "EntityRemovalSystem" that not only removes (for example MOT beam entities) but also makes sure that corresponding entries in all the vectors are set to 0 or similar.  Pro: minimal runtime impact, Con: More prone to errors

I believe this topic becomes more and more important as we move towards simulation files that combine various side-arm stages.

What do you think?

**Comment by ElliotB256** [comment]
Related to #27. For the record I think dynamical components should be cleared each step, although there is a slight overhead from doing so. At the very least we should improve the tests surrounding similar components so that they can catch this problem.

**Comment by MauriceZeuner** [comment]
would you be happy to have a short chat about that?

**Comment by ElliotB256** [comment]
sure!

**Comment by ElliotB256** [comment]
We never had the chat so I'll clarify my thoughts here.

There should *not* be an `EntityRemovalSystem` that does everything, because doing so would tightly couple all the modules together. Instead, `ToBeDestroyed` component should be attached to signal intent, and then modules can behave appropriately to handle entity deletion.

Regardless, the real issue here was that a component used for aggregation was not being cleared each frame. We already do approach (1) for `Force` and other things, so the fix should be to add a system to clear whatever component needed clearing each frame.

**Comment by MauriceZeuner** [comment]
Okay, so you mean, I just implement a `ClearComponentSystem` for every `Component` that needs to be cleared, completely analogue to `ClearForceSystem`?

**Comment by MauriceZeuner** [comment]
Done in #48

**Comment by ElliotB256** [comment]
Please don't close the issue until it has been merged into master.

**Comment by MauriceZeuner** [comment]
I'd say it's already merged in #48 or is that not what you meant?

**Comment by ElliotB256** [comment]
Ahh sorry, my mistake! yes, this can close
