### ISSUE TITLE
Multiple atomic transitions

### ISSUE THREAD

**Issue by damienBloch** [TeamAtomECS/AtomECS#46]
What is the correct way to generate atoms from an oven with multiple transitions ?

I assumed that I could just add an AtomicTransition component to the oven creation, but it doesn't seem to work.

For example, replacing in 2d_plus_mot_from_oven the line

`l156: .with(AtomicTransition::strontium())` 

either by 

`l156: .with(AtomicTransition::strontium())` 
`l157: .with(AtomicTransition::strontium_red())` 

or 

`l157: .with(AtomicTransition::strontium_red())` 
`l156: .with(AtomicTransition::strontium())` 

doesn't give the same simulation results in the two cases.

It seems that in the first case, adding the red transition overwrites the blue.

**Comment by ElliotB256** [comment]
This is indeed a limitation of the current code, that we can only have one transition per atom!

## Short term workaround 

For now we are modelling setups with blue/red by basically swapping the `AtomicTransition` either spatially, eg on entities that go into the red region, or in time, eg doing it at a certain point in time. That is a workaround at best.

## Longer term feature implementation

Currently the rate equation implementation assumes a two-level system. For various components used in the rate force calcs, eg `TotalScatteredPhotons`, these enforce being a single transition (really this is the total scattered photons on a patricular atomic transition).

One easy implementation could be to introduce generic components for the transitions, for example `TotalScatteredPhotons<Sr461>`. Variants of the systems could be readily introduced for each transition, so that all the transitions occur in parallel for each allowed transition, eg `CalculateTotalScatteredPhotons<Sr461>`.

**Comment by ElliotB256** [comment]
Sketching out the details of a possible implementation.

* `AtomicTransition` becomes a Trait which defines properties of an atomic transition. These would have to be functions, but they all return constant values when evaluated so we determined at compile time.
* A macro generates definitions for empty tag component structs such as `Strontium461`. _These hold no data_ (and hence execution may actually speed up), and the macro makes an implementation of the `AtomicTransition` trait for this struct.
* Components related to the force calculation for a particular transition must be defined for that type, eg `TwoLevelPopulation<Strontium461>` would define a component that stores the two-level populations for the Strontium 461 transition.
* Systems related to the force calculation must be defined for that type, eg `CalculateTwoLevelPopulation<Strontium461>`.
* Most of this definition can be automatically handled by `atomecs`. The only user change would be adding a component for laser cooling on that transition, eg adding `Strontium461` to the atom, instead of the `AtomicTransition` component.
* A disadvantage is the user will now have to explicitly register transitions to simulate. In most cases, this is minor and probably tolerable. eg `ecs::create_simulation_dispatcher_builder.for_cooling<Strontium461>()`

_An aside is that component names could get nasty. For instance, what about different isotopes?_

**Comment by ElliotB256** [comment]
Other thoughts:
* This is very contingent on using the 'two level' approximation even for multiple cooling transitions. It won't be able to model effects of saturation/population pumping between those transitions. For that reason, it should be `TwoLevelAtomicTransition`
* Future atomecs may support multiple ways of calculating scattering forces, eg OBE or multi-level rate equation (MLRE). For this reason, the ecs dispatcher syntax may benefit from being explicit - `.using_two_level_model<Strontium461>()`. Alternatively, we can leave that and address it when a new model is added, as for now there is only one model.

**Comment by ElliotB256** [comment]
I've added this to the 3D MOT milestone because it's required for doing two-stage cooling for strontium.

**Comment by ElliotB256** [comment]
I've started the [transition_trait](https://github.com/TeamAtomECS/AtomECS/tree/transition_trait) branch to work on this. It doesn't yet compile but I'm close
c506fde

An unintended side effect is that this exposes `specs` lack of a way to clone entities, or produce entities from a template, which has led to some rigidity in how we spawn atoms. Currently atoms use the `AtomicTransition` attached to the oven, which is clearly a bit strange. Changing `AtomicTransition` to a trait now means we must define ovens with a generic argument, which is less than ideal.

**Comment by ElliotB256** [comment]
Now compiles and runs the 1dmot example. For now I've left some things hard coded (e.g. only systems added for Sr88)

**Comment by ElliotB256** [comment]
Tagging @MauriceZeuner back in

**Comment by ElliotB256** [comment]
Added !transition and !species macros:
```
species!(Strontium88, Strontium88_461, 88);
transition!(Strontium88_461, 650_759_219_088_937.0, 32e6, 430.0, BOHRMAG, -BOHRMAG, 0.0);
```

**Comment by ElliotB256** [comment]
It would be interesting to hear any opinions on this approach. Conceptually I still like the idea - it allows you to define multiple two-level models which can be evaluated independently. It also opens us up to other models in the future, e.g. a Bloch Equation solver for one transition and a two-level solver for another.

**Comment by ElliotB256** [comment]
IMO the big issue for now is usability - it makes setting up the systems less 'out of the box'. I think the solution will come in the form of the plugin workflow of #73. That would let you add plugins for e.g. a two-level system on `Rb87_D2`, for instance.

**Comment by ElliotB256** [comment]
Appreciate thoughts from @minghuaw

**Comment by ElliotB256** [comment]
I need a better way to handle system dependencies for the plugin. Current dependency is indicated by strings, e.g. `calculate_absorption_forces`

**Comment by ElliotB256** [comment]
I rewrote the modules to use a Plugin based workflow, e.g.:

```
    let mut world = World::new();
    ecs::register_components(&mut world);
    ecs::register_resources(&mut world);
    let mut builder =
        ecs::create_simulation_dispatcher_builder::<{ lib::laser::DEFAULT_BEAM_LIMIT }>();

    // Add some output to the simulation
    builder = builder.with(
        file::new::<Position, Text>("pos.txt".to_string(), 10),
        "",
        &[],
    );
    builder = builder.with(
        file::new::<Velocity, Text>("vel.txt".to_string(), 10),
        "",
        &[],
    );

    let mut dispatcher = builder.build();
    dispatcher.setup(&mut world);
```
becomes
```
    let mut sim_builder = SimulationBuilder::default();
    sim_builder.add_plugin(FileOutputPlugin::<Position, Text, Atom>::new("pos.txt".to_string(), 10));
    sim_builder.add_plugin(FileOutputPlugin::<Velocity, Text, Atom>::new("vel.txt".to_string(), 10));
    let mut sim = sim_builder.build();
```

**Comment by ElliotB256** [comment]
Most of the plugins look similar to this - they register required resources and add required systems:
```
pub struct MagneticsPlugin;
impl Plugin for MagneticsPlugin {
    fn build(&self, builder: &mut crate::simulation::SimulationBuilder) {
        add_systems_to_dispatch(&mut builder.dispatcher_builder, &[]);
        register_components(&mut builder.world);
    }
}
```

**Comment by ElliotB256** [comment]
The plugin workflow could be improved to provide extra flexibility - e.g. to add different stages to the dispatcher. Given that we may still change the ECS backend in the future, and bevy already supports solutions for this, let's delay that fix for a while.

**Comment by ElliotB256** [comment]
Unit tests now working and I've fixed most of the examples. @d-garrick can you take a look at the magnetics examples, I've fixed up the Quadruple trap one - please see the todo note therein about making a `MagneticConfinementPlugin`.

**Comment by ElliotB256** [comment]
@d-garrick you will also need aea8a8e

**Comment by ElliotB256** [comment]
Checking for performance changes after rewrite:
```
cargo run --example benchmark --release
```

current master:
```
Simulation loop completed in 13348 ms.
```

transitions rewrite:
```
Simulation loop completed in 10321 ms.
```

So there is a slight performance improvement. This is probably because:
* We can now tailor plugin composition more easily (less overhead from unused systems).
* Transition components now have no size in memory.
* The laser array size can now be tailored for the specific simulation.

**Comment by ElliotB256** [comment]
I've also added some ability to resolve interdependencies between plugins - so it will at least panic if you require a plugin you have not yet added.
